/* Asset catalogue generator.
   Writes docs/asset-catalogue.md straight from the registry, so the documented
   asset list can never drift from the assets. Re-run after adding a pack:

     node scripts/catalogue.js

   Usage: node scripts/catalogue.js [--check]
          --check exits non-zero if the file on disk is out of date (CI gate).
*/
const fs = require('fs');
const path = require('path');
const { boot, ROOT } = require('./lib-boot');

const PF = boot();
const check = process.argv.includes('--check');

const CATEGORY_ORDER = ['Heroes', 'Enemies', 'NPCs', 'Animals', 'World', 'Items', 'FX', 'UI'];
const list = PF.Library.list();
const byCat = new Map(CATEGORY_ORDER.map(c => [c, []]));
for (const t of list) {
  if (!byCat.has(t.category)) byCat.set(t.category, []);
  byCat.get(t.category).push(t);
}
const stats = new Map(list.map(t => [t.id, PF.Library.docStats(t.id)]));
const total = { templates: list.length, states: 0, frames: 0 };
for (const s of stats.values()) { total.states += s.states; total.frames += s.frames; }

/* Genre roll-up: what a developer can actually build, not how it is filed. */
const GENRE_TAGS = ['platformer', 'rpg', 'fantasy', 'medieval', 'scifi', 'cyberpunk', 'horror', 'zombie',
  'farm', 'farming', 'urban', 'city', 'nature', 'forest', 'jungle', 'ocean', 'space', 'shooter', 'tiny',
  'handheld', 'autotile', 'tiles', 'ui', 'font', 'fx', 'vehicle', 'animal', 'survival', 'rts', 'puzzle'];
const genre = new Map();
for (const t of list) for (const tag of t.tags) if (GENRE_TAGS.includes(tag)) {
  genre.set(tag, (genre.get(tag) || 0) + 1);
}

const TAG_ROW = [...genre.entries()].sort((a, b) => b[1] - a[1] || (a[0] < b[0] ? -1 : 1));

const lines = [];
lines.push('# Asset catalogue');
lines.push('');
lines.push(`Generated by \`node scripts/catalogue.js\` — **${total.templates} templates · ${total.states} animation states · ${total.frames} frames**, all drawn at runtime from code.`);
lines.push('');
lines.push('> Do not edit by hand: run the generator. `scripts/check-docs.js` fails if this file is stale.');
lines.push('');
lines.push('## What you can build');
lines.push('');
lines.push('| genre / tag | templates |');
lines.push('|---|---|');
for (const [tag, n] of TAG_ROW) lines.push(`| \`${tag}\` | ${n} |`);
lines.push('');
lines.push('## Categories');
lines.push('');
for (const cat of CATEGORY_ORDER) {
  const items = byCat.get(cat) || [];
  if (!items.length) continue;
  lines.push(`### ${cat} (${items.length})`);
  lines.push('');
  lines.push('| id | name | size | states | frames | tags |');
  lines.push('|---|---|---|---|---|---|');
  for (const t of items) {
    const s = stats.get(t.id);
    lines.push(`| \`${t.id}\` | ${t.name} | ${s.width}×${s.height} | ${s.states} | ${s.frames} | ${t.tags.join(', ')} |`);
  }
  lines.push('');
}
lines.push('## Animation state vocabulary');
lines.push('');
const vocab = new Map();
for (const t of list) for (const s of stats.get(t.id).stateNames) vocab.set(s, (vocab.get(s) || 0) + 1);
const common = [...vocab.entries()].sort((a, b) => b[1] - a[1]).slice(0, 40);
lines.push('Consumers drive animation by state name, so the vocabulary is shared across packs.');
lines.push('The most common state names:');
lines.push('');
lines.push('```');
lines.push(common.map(([n, c]) => `${n} (${c})`).join('  ·  '));
lines.push('```');
lines.push('');
lines.push('Locomotion is `idle_*`, `walk_*`, `run_*` (`_down` / `_side` / `_up`, or `_e`/`_se`/… on the 8-facing RTS packs).');
lines.push('Combat is `attack_*`, `bow_side`, `cast`, `cast_side`, `block`, `ready_*`, `parry_*`, `evade_*`.');
lines.push('Reaction is `hurt` and `death` (`loop: false`).');
lines.push('');

const text = lines.join('\n');
const out = path.join(ROOT, 'docs/asset-catalogue.md');

if (check) {
  const cur = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : '';
  if (cur !== text) { console.log('docs/asset-catalogue.md is out of date — run: node scripts/catalogue.js'); process.exit(1); }
  console.log(`asset catalogue up to date (${total.templates} templates)`);
  process.exit(0);
}
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, text);
console.log(`wrote docs/asset-catalogue.md — ${total.templates} templates · ${total.states} states · ${total.frames} frames`);
