/* Hearthhold — a settlement that has to survive the nights.

   Build the valley by day: fell timber, quarry stone, raise dwellings so your
   people have beds and a granary so they have food. Then hold it after dark,
   because from the second night raiders come down the four approaches and
   they will take the hall apart if nothing stops them.

   The three layers are kept honestly separate. defs.js is data, world.js is
   the grid and the route finder, and this file is the simulation, the chrome
   and the render loop. Nothing here loads an image: every pixel on screen is
   generated by a PixelForge template at boot and cached as a canvas.

   The one structural idea worth knowing before reading on: villagers are a
   flat list of small objects driven by a single-step state machine, and they
   never plan further than "walk to this tile, then do this one thing". All the
   apparent intelligence — foresters cutting the nearest stand, haulers filling
   the storehouse, everyone going to bed at dusk — comes from re-running that
   one-step decision whenever a villager finishes what it was doing. There is
   no scheduler and no behaviour tree to keep in sync. */
(() => {
  'use strict';

  const $ = s => document.querySelector(s);
  const { T, MW, MH, G, RES, RES_NAME, RES_COLOUR, RES_ICON, NODES, CATS, BUILD,
    byId, HALL, NAMES, RAIDER_KINDS, DIFFS, faceOf, WIN_DAY } = window.HH;
  const W = window.HHWorld;

  const clamp = (v, a, b) => (v < a ? a : v > b ? b : v);
  const lerp = (a, b, t) => a + (b - a) * t;
  const TAU = Math.PI * 2;

  /* --------------------------------------------------------------- audio -- */

  /* Every sound is synthesised. There are no audio files in this project and
     adding one would be the only asset in the repository. */
  const SFX = (() => {
    let ctx = null, muted = false;
    const on = () => {
      if (ctx) return ctx;
      const AC = window.AudioContext || window.webkitAudioContext;
      if (!AC) return null;
      try { ctx = new AC(); } catch { ctx = null; }
      return ctx;
    };
    function tone(freq, dur, type, gain, slide) {
      if (muted) return;
      const c = on(); if (!c) return;
      const o = c.createOscillator(), g = c.createGain();
      o.type = type || 'square';
      o.frequency.setValueAtTime(freq, c.currentTime);
      if (slide) o.frequency.exponentialRampToValueAtTime(Math.max(40, slide), c.currentTime + dur);
      g.gain.setValueAtTime(gain === undefined ? 0.05 : gain, c.currentTime);
      g.gain.exponentialRampToValueAtTime(0.0001, c.currentTime + dur);
      o.connect(g); g.connect(c.destination);
      o.start(); o.stop(c.currentTime + dur);
    }
    function noise(dur, gain, hp) {
      if (muted) return;
      const c = on(); if (!c) return;
      const n = Math.floor(c.sampleRate * dur);
      const buf = c.createBuffer(1, n, c.sampleRate);
      const d = buf.getChannelData(0);
      for (let i = 0; i < n; i++) d[i] = (Math.random() * 2 - 1) * (1 - i / n);
      const src = c.createBufferSource(); src.buffer = buf;
      const f = c.createBiquadFilter(); f.type = hp ? 'highpass' : 'lowpass';
      f.frequency.value = hp || 900;
      const g = c.createGain(); g.gain.value = gain === undefined ? 0.06 : gain;
      src.connect(f); f.connect(g); g.connect(c.destination);
      src.start();
    }
    return {
      place: () => { tone(320, 0.07, 'square', 0.04); tone(480, 0.09, 'square', 0.03); },
      deny: () => tone(150, 0.12, 'sawtooth', 0.05, 90),
      done: () => { tone(520, 0.08, 'triangle', 0.05); tone(780, 0.12, 'triangle', 0.04); },
      chop: () => noise(0.09, 0.05, 0),
      hit: () => noise(0.07, 0.07, 1400),
      bow: () => tone(880, 0.06, 'triangle', 0.03, 400),
      horn: () => { tone(180, 0.5, 'sawtooth', 0.06, 130); tone(240, 0.45, 'square', 0.03, 170); },
      dawn: () => { tone(440, 0.12, 'triangle', 0.04); tone(660, 0.18, 'triangle', 0.035); },
      pick: () => tone(700, 0.04, 'square', 0.03),
      on,
      toggle(v) { muted = v === undefined ? !muted : !!v; return muted; },
      get muted() { return muted; }
    };
  })();

  /* -------------------------------------------------------------- sprites -- */

  /* Everything the renderer will ever draw, baked once. Slicing the tile and
     autotile sheets up front means the hot loop only ever does drawImage of a
     16x16 canvas, never a sub-rect of a bigger one. */
  const ART = { ready: false };
  function bakeArt() {
    if (ART.ready) return;
    ART.ground = GB.sliceTiles('hold_ground', 'sheet', 16, 16, 4);
    ART.palisade = GB.sliceTiles('hold_palisade', 'sheet', 16, 16, 4);
    ART.rampart = GB.sliceTiles('hold_rampart', 'sheet', 16, 16, 4);
    ART.ready = true;
  }
  const spr = (id, state, t) => GB.at(id, state, t || 0);
  const sprFrame = (id, state, i) => GB.frame(id, state, i || 0);

  /* ---------------------------------------------------------------- state -- */

  const S = {
    world: null, diff: DIFFS[1], res: {}, cap: 0,
    folk: [], raiders: [], arrows: [], pops: [], sparks: [],
    builds: new Map(), nextId: 1, hall: null,
    day: 1, hour: 7, dayLen: 90, night: false, rain: 0, rainT: 0,
    speed: 1, running: false, over: false, won: false,
    cheer: 60, cheerTarget: 60,
    tool: null, cat: 'home', drag: null, hover: { x: -1, y: -1 },
    sel: null, cam: { x: 0, y: 0 }, zoom: 3,
    score: 0, kills: 0, raised: 0, lost: 0, wave: 0, waveNight: 0,
    t: 0, prodT: 0, growT: 0, msg: '', msgT: 0
  };

  /* ------------------------------------------------------------- elements -- */

  const cv = $('#cv'), ctx = cv.getContext('2d');
  const el = {
    hud: $('#hud'), toast: $('#toast'), clock: $('#clock-txt'), day: $('#day-txt'),
    pop: $('#pop-txt'), cheerFill: $('#cheer-fill'), cheerArrow: $('#cheer-arrow'),
    score: $('#score-txt'), rail: $('#cat-rail'), palette: $('#palette'),
    card: $('#card'), cardName: $('#card-name'), cardCost: $('#card-cost'), cardDesc: $('#card-desc'),
    insp: $('#inspect'), banner: $('#wave-txt'),
    title: $('#screen-title'), picker: $('#picker'), best: $('#best-txt'),
    over: $('#screen-over'), overTitle: $('#over-title'), overSub: $('#over-sub'),
    overStats: $('#over-stats'), again: $('#btn-again'),
    mute: $('#btn-mute'), pause: $('#btn-pause'), res: $('#res-strip')
  };

  const mk = (tag, cls, parent, text) => {
    const e = document.createElement(tag);
    if (cls) e.className = cls;
    if (text !== undefined) e.textContent = text;
    if (parent) parent.appendChild(e);
    return e;
  };

  /* ------------------------------------------------------------ resources -- */

  const resEl = {};
  function buildResStrip() {
    for (const r of RES) {
      const chip = mk('div', 'chip', el.res);
      const ic = mk('canvas', 'ic', chip);
      ic.width = 20; ic.height = 20;
      const g = ic.getContext('2d');
      g.imageSmoothingEnabled = false;
      const [sid, sst] = RES_ICON[r];
      const f = sprFrame(sid, sst, 0);
      if (f) g.drawImage(f.cv, 0, 0, f.w, f.h, 0, 0, 20, 20);
      resEl[r] = mk('b', null, chip, '0');
      chip.title = RES_NAME[r];
    }
  }

  const has = cost => RES.every(r => (S.res[r] || 0) >= (cost[r] || 0));
  function spend(cost) {
    for (const r of RES) if (cost[r]) S.res[r] -= cost[r];
  }
  function gain(r, n) {
    if (!r) return;
    const room = r === 'coin' ? Infinity : S.cap;
    S.res[r] = Math.min(room, (S.res[r] || 0) + n);
  }
  const costText = cost => RES.filter(r => cost[r]).map(r => cost[r] + ' ' + RES_NAME[r]).join('  ') || 'free';

  /* ------------------------------------------------------------ buildings -- */

  function footprint(def, x, y, fn) {
    for (let j = 0; j < def.fh; j++) for (let i = 0; i < def.fw; i++) fn(x + i, y + j);
  }

  /* A placement is legal when every tile it covers is on the map, dry, empty
     of nodes and structures, and — for anything with a footprint — not on top
     of a wall. Roads are the exception: they are ground, so they may be laid
     over anything walkable. */
  function canPlace(def, x, y) {
    if (def.demolish) {
      const i = W.idx(x, y);
      return W.inb(x, y) && (S.world.occ[i] !== 0 || S.world.wall[i] !== 0 ||
        S.world.ground[i] === G.ROAD || S.world.ground[i] === G.COBBLE);
    }
    let ok = true;
    footprint(def, x, y, (px, py) => {
      if (!W.inb(px, py)) { ok = false; return; }
      const i = W.idx(px, py);
      if (W.isWater(S.world, i) || S.world.ground[i] === G.SHALLOW) { ok = false; return; }
      if (S.world.occ[i]) { ok = false; return; }
      if (def.ground) return;                        // groundworks only need dry land
      /* A gate is meant to be dropped straight into a finished wall line —
         making the player demolish two stakes first is busywork. */
      if (S.world.wall[i] && !(def.gate && S.world.wall[i] !== 3)) { ok = false; return; }
      if (S.world.node[i]) { ok = false; return; }
    });
    return ok;
  }

  /* Dragging a wall line along a forest edge refuses on every tile it crosses.
     One buzz per burst is feedback; a dozen in a second is a machine gun. */
  let refuseT = -9;
  function refuse(msg) {
    if (S.t - refuseT > 0.4) { SFX.deny(); refuseT = S.t; }
    toast(msg);
    return false;
  }

  function place(def, x, y) {
    if (def.demolish) return demolish(x, y);
    if (!canPlace(def, x, y)) return refuse('No room for that here');
    if (!has(def.cost)) return refuse('Not enough ' + shortfall(def.cost));
    spend(def.cost);

    if (def.ground) {                                 // roads are pure terrain
      S.world.ground[W.idx(x, y)] = def.ground;
      dirtyGround();
      SFX.place();
      return true;
    }
    if (def.gate) footprint(def, x, y, (px, py) => {      // swallow the wall it replaces
      const under = findStructure(px, py);
      if (under && under.def.wall && under.def.wall !== 3) removeBuild(under, false);
      S.world.wall[W.idx(px, py)] = 0;
    });
    const b = {
      id: S.nextId++, def, x, y, hp: Math.max(8, Math.round(def.hp * 0.3)), maxHp: def.hp,
      done: false, prog: 0, work: def.build, staff: [], gateMode: 'auto', open: false,
      timer: 0, anim: Math.random() * 3
    };
    S.builds.set(b.id, b);
    footprint(def, x, y, (px, py) => {
      const i = W.idx(px, py);
      if (def.wall) S.world.wall[i] = def.wall;
      else S.world.occ[i] = b.id;
      if (def.field) { S.world.crop[i] = 1; S.world.cropT[i] = 0; S.world.ground[i] = G.TILL; }
    });
    if (def.field) dirtyGround();
    recomputeCaps();
    SFX.place();
    return true;
  }

  function shortfall(cost) {
    return RES.filter(r => (cost[r] || 0) > (S.res[r] || 0))
      .map(r => RES_NAME[r].toLowerCase()).join(' or ');
  }

  function demolish(x, y) {
    const i = W.idx(x, y);
    const id = S.world.occ[i];
    if (id && S.builds.has(id)) {
      const b = S.builds.get(id);
      if (b.def === HALL) { SFX.deny(); toast('The hall cannot be pulled down'); return false; }
      refund(b.def);
      removeBuild(b, false);
      SFX.place();
      return true;
    }
    if (S.world.wall[i]) {
      /* A gate is one building across two tiles, so pulling on either tile has
         to take the whole thing with it. Clearing just this square left a
         half-gate that still governed passage and could be refunded again from
         the other half. */
      const b = findStructure(x, y);
      if (b) { refund(b.def); removeBuild(b, false); }
      else S.world.wall[i] = 0;
      SFX.place();
      return true;
    }
    if (S.world.ground[i] === G.ROAD || S.world.ground[i] === G.COBBLE) {
      S.world.ground[i] = G.GRASS; dirtyGround(); SFX.place(); return true;
    }
    return false;
  }

  const refund = def => { for (const r of RES) if (def.cost[r]) gain(r, Math.floor(def.cost[r] / 3)); };

  function removeBuild(b, razed) {
    footprint(b.def, b.x, b.y, (px, py) => {
      if (!W.inb(px, py)) return;
      const i = W.idx(px, py);
      if (S.world.occ[i] === b.id) S.world.occ[i] = 0;
      if (b.def.wall) S.world.wall[i] = 0;
      if (b.def.field) { S.world.crop[i] = 0; S.world.ground[i] = razed ? G.ASH : G.GRASS; }
      if (razed && !b.def.wall) S.world.ground[i] = G.ASH;
    });
    if (b.def.field || razed) dirtyGround();
    S.builds.delete(b.id);
    for (const v of S.folk) {
      if (v.place === b.id) { v.place = 0; v.job = null; }
      if (v.home === b.id) v.home = 0;
    }
    if (S.sel && S.sel.kind === 'build' && S.sel.ref === b) { S.sel = null; showInspect(null); }
    recomputeCaps();
    if (b.def === HALL) lose('The hall has fallen.');
  }

  /* Storage headroom, bed count and the standing happiness bonus all derive
     from whatever is currently finished, so they are recomputed on any change
     to the building set rather than tracked incrementally — incremental
     bookkeeping is what produces a settlement with negative beds. */
  function recomputeCaps() {
    let cap = 0, beds = 0, cheer = 0, guard = 0, arms = 0;
    for (const b of S.builds.values()) {
      if (!b.done) continue;
      cap += b.def.store || 0;
      beds += b.def.house || 0;
      cheer += b.def.cheer || 0;
      guard += b.def.guard || 0;
      arms = Math.max(arms, b.def.arms || 0);
    }
    S.cap = 200 + cap; S.beds = beds; S.buildCheer = cheer; S.guardCap = guard; S.arms = arms;
  }

  /* ------------------------------------------------------------- villagers -- */

  let nameSeq = 0;
  function addFolk(x, y, role) {
    const v = {
      id: S.nextId++, name: NAMES[nameSeq++ % NAMES.length],
      x, y, role: role || 'worker',
      hp: role === 'soldier' ? 70 : 42, maxHp: role === 'soldier' ? 70 : 42,
      atk: role === 'soldier' ? 10 + (S.arms || 0) : 3,
      work: 1, face: 'down', anim: Math.random() * 4,
      path: null, pi: 0, tx: x, ty: y,
      state: 'idle', timer: 0, carry: null, place: 0, home: 0,
      cd: 0, asleep: false, hurtT: 0
    };
    S.folk.push(v);
    return v;
  }

  const tileOf = v => W.idx(clamp(Math.round(v.x), 0, MW - 1), clamp(Math.round(v.y), 0, MH - 1));

  /* Walk one step of the current path. Returns true on arrival. A path that
     has gone stale — a wall raised across it, a building dropped on it — is
     dropped rather than repaired, and the caller's next decision tick picks a
     fresh one. This is why villagers occasionally pause for a beat when you
     wall them in, and why they never walk through the wall. */
  function advance(v, dt, speed) {
    if (!v.path || v.pi >= v.path.length) return true;
    const ti = v.path[v.pi];
    const tx = ti % MW, ty = ti / MW | 0;
    const dx = tx - v.x, dy = ty - v.y;
    const d = Math.hypot(dx, dy);
    if (d < 0.08) {
      v.pi++;
      if (v.pi >= v.path.length) { v.path = null; return true; }
      return false;
    }
    const road = W.isRoad(S.world, tileOf(v)) ? 1.45 : 1;
    const step = Math.min(d, speed * road * dt);
    v.x += dx / d * step; v.y += dy / d * step;
    v.face = faceOf(dx, dy);
    v.anim += dt * 6;
    return false;
  }

  function goTo(v, ti, opts) {
    const tx = ti % MW, ty = ti / MW | 0;
    const p = W.route(S.world, Math.round(v.x), Math.round(v.y), tx, ty,
      Object.assign({ gateOpen: gi => gateOpenAt(gi) }, opts || {}));
    v.path = p; v.pi = 0; v.tx = tx; v.ty = ty;
    return !!p;
  }

  const gateOpenAt = i => {
    const id = S.world.occ[i];
    for (const b of S.builds.values())
      if (b.def.gate && b.x <= (i % MW) && (i % MW) < b.x + b.def.fw && b.y === (i / MW | 0))
        return b.open && b.done;
    return id === 0;
  };

  /* The single decision point. Called whenever a villager has nothing to do;
     everything above it is movement and everything below is the one action it
     chose. Order matters — it is the priority list. */
  function decide(v) {
    v.path = null; v.timer = 0;

    /* A hurt villager is skittish, not catatonic: it bolts from further off
       than a healthy one but still needs something to bolt from. Fleeing on the
       wound alone wedged it forever, because hit points only come back in bed
       and this test ran before the decision to go to bed. */
    if (v.role !== 'soldier' && nearestRaider(v.x, v.y, v.hp < v.maxHp * 0.45 ? 9 : 6)) {
      v.state = 'flee'; v.timer = 0; return;
    }

    // 1. soldiers hold the line and never take a shift
    if (v.role === 'soldier') { v.state = 'guard'; return; }

    // 2. sleep: at night, in a bed if there is one
    if (S.night && !v.asleep) {
      const home = S.builds.get(v.home);
      if (home && home.done) {
        if (goTo(v, W.idx(home.x, home.y + home.def.fh - 1))) { v.state = 'tobed'; return; }
      }
      v.state = 'tobed'; v.asleep = true; return;
    }
    if (S.night) { v.state = 'sleep'; return; }

    // 3. finish what is half-built before starting anything new
    const site = nearestSite(v);
    if (site) {
      if (goTo(v, W.idx(site.x, site.y + site.def.fh - 1))) { v.state = 'tobuild'; v.job = site.id; return; }
    }

    // 4. drop what is being carried
    if (v.carry && v.carry.n > 0) {
      const drop = nearestStore(v);
      if (drop && goTo(v, W.idx(drop.x, drop.y + drop.def.fh - 1))) { v.state = 'haul'; return; }
      gain(v.carry.res, v.carry.n); v.carry = null;    // nowhere to put it: count it anyway
    }

    // 5. work the assigned trade
    const place = S.builds.get(v.place);
    if (place && place.done) {
      if (place.def.field) { if (fieldJob(v, place)) return; }
      else if (place.def.gather) { if (gatherJob(v, place)) return; }
      else { v.state = 'tend'; goTo(v, W.idx(place.x, place.y + place.def.fh - 1)); return; }
    }

    // 6. unemployed: take any vacancy, else drift
    const job = openVacancy(v);
    if (job) { v.place = job.id; job.staff.push(v.id); decide(v); return; }
    v.state = 'wander';
    const spot = W.nearest(S.world, v.x + (Math.random() * 8 - 4), v.y + (Math.random() * 8 - 4),
      i => !W.blocked(S.world, i % MW, i / MW | 0, gateOpenAt), 6);
    if (spot !== null) goTo(v, spot);
  }

  function nearestSite(v) {
    let best = null, bd = 1e9;
    for (const b of S.builds.values()) {
      if (b.done) continue;
      const d = Math.hypot(b.x - v.x, b.y - v.y);
      if (d < bd) { bd = d; best = b; }
    }
    return best;
  }

  function nearestStore(v) {
    let best = null, bd = 1e9;
    for (const b of S.builds.values()) {
      if (!b.done || !(b.def.store || b.def === HALL)) continue;
      const d = Math.hypot(b.x - v.x, b.y - v.y);
      if (d < bd) { bd = d; best = b; }
    }
    return best || S.hall;
  }

  const feedsUs = def => def.field === 'crop' || (def.gather && def.gather.indexOf('wild') >= 0);

  /* Vacancies are filled by need, not by build order: the emptiest workplace
     wins, a food building outranks everything while the stores are low, and
     distance breaks the tie. Handing out the first free slot in insertion
     order is what leaves a brand-new field standing idle because three people
     are already crowding the first lodge you ever placed. */
  function openVacancy(v) {
    let best = null, bs = -1e9;
    const hungry = (S.res.food || 0) < S.folk.length * 14;
    for (const b of S.builds.values()) {
      if (!b.done || !b.def.jobs) continue;
      b.staff = b.staff.filter(id => S.folk.some(f => f.id === id && f.place === b.id));
      if (b.staff.length >= b.def.jobs) continue;
      let sc = (1 - b.staff.length / b.def.jobs) * 10;
      if (hungry && feedsUs(b.def)) sc += 14;
      sc -= Math.hypot(b.x - v.x, b.y - v.y) * 0.12;
      if (sc > bs) { bs = sc; best = b; }
    }
    return best;
  }

  /* Gatherers work outward from their lodge, not from wherever they happen to
     be standing, so a woodcutter clears the wood around itself instead of
     wandering across the valley chasing the single closest tree. */
  function gatherJob(v, place) {
    const kinds = place.def.gather;
    /* Walk down the nearest few nodes rather than demanding the closest one.
       A seam on the far shore is nearest and unreachable, and a gatherer that
       only ever asks for that one stands in the grass for the rest of the run. */
    const tried = new Set();
    for (let k = 0; k < 4; k++) {
      const ti = W.nearest(S.world, place.x, place.y, i => {
        if (tried.has(i)) return false;
        const d = W.nodeDef(S.world, i);
        return !!d && d.res && S.world.amt[i] > 0 && kinds.includes(d.kind);
      }, 20);
      if (ti === null) break;
      tried.add(ti);
      const adj = adjacentTo(v, ti);
      if (adj !== null && goTo(v, adj)) { v.state = 'togather'; v.job = ti; return true; }
    }
    v.state = 'tend'; goTo(v, W.idx(place.x, place.y));
    return true;
  }

  function fieldJob(v, place) {
    let ripe = -1;
    footprint(place.def, place.x, place.y, (px, py) => {
      const i = W.idx(px, py);
      if (ripe < 0 && S.world.crop[i] >= 5) ripe = i;
    });
    const ti = ripe >= 0 ? ripe : W.idx(place.x, place.y);
    const adj = adjacentTo(v, ti);
    if (adj === null || !goTo(v, adj)) { v.state = 'wander'; return true; }
    v.state = ripe >= 0 ? 'toharvest' : 'tofarm'; v.job = ti;
    return true;
  }

  /* A worker stands beside the thing it works on, never on it. */
  function adjacentTo(v, ti) {
    const tx = ti % MW, ty = ti / MW | 0;
    let best = null, bd = 1e9;
    for (const [dx, dy] of [[1, 0], [-1, 0], [0, 1], [0, -1], [1, 1], [-1, 1], [1, -1], [-1, -1]]) {
      const px = tx + dx, py = ty + dy;
      if (W.blocked(S.world, px, py, gateOpenAt)) continue;
      const d = Math.hypot(px - v.x, py - v.y);
      if (d < bd) { bd = d; best = W.idx(px, py); }
    }
    return best;
  }

  function tickFolk(v, dt) {
    if (v.hurtT > 0) v.hurtT -= dt;
    if (v.cd > 0) v.cd -= dt;
    const speed = (v.role === 'soldier' ? 3.0 : 2.4) * (0.75 + S.cheer / 200);

    switch (v.state) {
      case 'idle': decide(v); break;

      case 'wander':
      case 'tend':
        if (advance(v, dt, speed)) { v.timer += dt; if (v.timer > 1.6) decide(v); }
        break;

      case 'tobed':
        if (advance(v, dt, speed)) { v.state = 'sleep'; v.asleep = true; }
        break;
      case 'sleep':
        v.asleep = true;
        if (!S.starving) v.hp = Math.min(v.maxHp, v.hp + dt * 2.5);
        if (nearestRaider(v.x, v.y, 7)) { v.asleep = false; v.state = 'flee'; v.path = null; v.timer = 0; }
        else if (!S.night) { v.asleep = false; decide(v); }
        break;

      case 'tobuild':
        if (advance(v, dt, speed)) v.state = 'build';
        break;
      case 'build': {
        const b = S.builds.get(v.job);
        if (!b || b.done) { decide(v); break; }
        b.prog += dt * (1 + S.cheer / 150);
        if (Math.random() < dt * 3) SFX.chop();
        if (b.prog >= b.work) finishBuild(b);
        break;
      }

      case 'togather':
        if (advance(v, dt, speed)) { v.state = 'gather'; v.timer = 0; }
        break;
      case 'gather': {
        const i = v.job, d = W.nodeDef(S.world, i);
        if (!d || !d.res || S.world.amt[i] <= 0) { decide(v); break; }
        v.timer += dt * (0.7 + S.cheer / 140);
        v.face = faceOf((i % MW) - v.x, (i / MW | 0) - v.y);
        if (v.timer >= d.work) {
          v.timer = 0;
          S.world.amt[i]--;
          v.carry = v.carry && v.carry.res === d.res ? v.carry : { res: d.res, n: 0 };
          v.carry.n++;
          SFX.chop();
          if (S.world.amt[i] <= 0) exhaust(i);
          if (v.carry.n >= 6) decide(v);
        }
        break;
      }

      case 'tofarm':
        if (advance(v, dt, speed)) { v.state = 'farm'; v.timer = 0; }
        break;
      case 'farm':
        v.timer += dt;
        if (v.timer > 2.5) decide(v);
        break;
      case 'toharvest':
        if (advance(v, dt, speed)) { v.state = 'harvest'; v.timer = 0; }
        break;
      case 'harvest': {
        const i = v.job;
        if (S.world.crop[i] < 5) { decide(v); break; }
        v.timer += dt;
        if (v.timer > 1.1) {
          S.world.crop[i] = 1; S.world.cropT[i] = 0;
          v.carry = { res: 'food', n: 6 };
          popup(i % MW, i / MW | 0, '+6', RES_COLOUR.food);
          SFX.chop();
          decide(v);
        }
        break;
      }

      case 'haul':
        if (advance(v, dt, speed)) {
          if (v.carry) {
            gain(v.carry.res, v.carry.n);
            popup(v.x, v.y, '+' + v.carry.n, RES_COLOUR[v.carry.res]);
            S.score += v.carry.n;
            v.carry = null;
          }
          decide(v);
        }
        break;

      case 'guard': {
        const foe = nearestRaider(v.x, v.y, 11);
        if (foe) {
          const d = Math.hypot(foe.x - v.x, foe.y - v.y);
          if (d > 1.1) {
            if (!v.path) goTo(v, W.idx(clamp(Math.round(foe.x), 0, MW - 1), clamp(Math.round(foe.y), 0, MH - 1)));
            if (advance(v, dt, speed)) v.path = null;
            v.timer += dt;
            if (v.timer > 0.6) { v.timer = 0; v.path = null; }
          } else {
            v.face = faceOf(foe.x - v.x, foe.y - v.y);
            if (v.cd <= 0) {
              v.cd = 0.8; foe.hp -= v.atk; foe.hurtT = 0.2; SFX.hit();
              if (foe.hp <= 0) killRaider(foe);
            }
          }
        } else {
          const rally = rallyPoint();
          if (Math.hypot(rally.x - v.x, rally.y - v.y) > 3.5) {
            if (!v.path) goTo(v, W.idx(rally.x, rally.y));
            advance(v, dt, speed);
          } else { v.anim += dt * 2; v.path = null; }
        }
        break;
      }

      /* Running for a fixed rally point is what gets a village massacred: the
         raiders follow, everybody arrives at the same square and stands there.
         So a frightened villager runs directly AWAY from whoever is closest,
         re-picking a bolthole about once a second, and only goes back to work
         when there is nothing within nine tiles. An unarmed worker is faster
         than every raider except the archer, so this actually saves them. */
      case 'flee': {
        v.timer -= dt;
        const near = nearestRaider(v.x, v.y, 9);
        if (!near) { if (!v.path || v.timer <= 0) decide(v); else advance(v, dt, speed * 1.25); break; }
        if (v.timer <= 0 || !v.path) {
          v.timer = 0.9;
          const ax = v.x - near.x, ay = v.y - near.y;
          const d = Math.hypot(ax, ay) || 1;
          const gx = clamp(Math.round(v.x + ax / d * 9), 1, MW - 2);
          const gy = clamp(Math.round(v.y + ay / d * 9), 1, MH - 2);
          const spot = W.nearest(S.world, gx, gy,
            i => !W.blocked(S.world, i % MW, i / MW | 0, gateOpenAt), 9);
          if (spot !== null) goTo(v, spot);
        }
        advance(v, dt, speed * 1.25);
        break;
      }

      default: decide(v);
    }
  }

  function exhaust(i) {
    const key = W.nodeKey(S.world, i), d = NODES[key];
    if (d.stump) W.setNode(S.world, i, 'stump');
    else if (d.regrow) { W.setNode(S.world, i, key, 0); S.world.regrow[i] = d.regrow; }
    else W.setNode(S.world, i, null);
  }

  function rallyPoint() {
    for (const b of S.builds.values()) if (b.done && b.def.rally) return { x: b.x, y: b.y };
    return S.hall ? { x: S.hall.x, y: S.hall.y + 2 } : { x: MW >> 1, y: MH >> 1 };
  }

  function finishBuild(b) {
    b.done = true; b.prog = b.work; b.hp = b.maxHp;
    S.raised++;
    recomputeCaps();
    assignHomes();
    SFX.done();
    toast(b.def.name + ' raised');
  }

  /* Beds are handed out nearest-first each time the housing stock changes, so
     a new cottage actually shelters the people standing next to it. */
  function assignHomes() {
    const beds = [];
    for (const b of S.builds.values())
      if (b.done && b.def.house) for (let k = 0; k < b.def.house; k++) beds.push(b);
    for (const v of S.folk) v.home = 0;
    for (const b of beds) {
      let best = null, bd = 1e9;
      for (const v of S.folk) {
        if (v.home) continue;
        const d = Math.hypot(b.x - v.x, b.y - v.y);
        if (d < bd) { bd = d; best = v; }
      }
      if (best) best.home = b.id;
    }
  }

  /* --------------------------------------------------------------- raiders -- */

  function spawnWave() {
    S.wave++;
    const power = (2 + S.wave * 1.6) * S.diff.raid;
    const gate = S.world.gates[(S.wave + 1) % S.world.gates.length];
    let budget = power;
    let n = 0;
    while (budget > 0 && n < 40) {
      const pool = RAIDER_KINDS.filter(k => k.worth <= budget + 3);
      const k = pool[Math.floor(Math.random() * pool.length)] || RAIDER_KINDS[0];
      budget -= k.worth * 0.55;
      const ang = Math.random() * TAU, r = Math.random() * 2.5;
      S.raiders.push({
        id: S.nextId++, kind: k,
        x: clamp(gate.x + Math.cos(ang) * r, 1, MW - 2),
        y: clamp(gate.y + Math.sin(ang) * r, 1, MH - 2),
        hp: k.hp * (1 + S.wave * 0.09), maxHp: k.hp * (1 + S.wave * 0.09),
        face: 'down', anim: Math.random() * 4, path: null, pi: 0,
        cd: 0, hurtT: 0, repath: 0, target: null
      });
      n++;
    }
    SFX.horn();
    toast('Raiders on the ' + gateName(gate) + ' road');
    banner('RAID ' + S.wave);
  }

  const gateName = g => (g.y < 4 ? 'north' : g.y > MH - 5 ? 'south' : g.x < 4 ? 'west' : 'east');

  /* Raiders are here for the settlement, not for a manhunt. They go for the
     nearest standing structure and only break off for a villager who is
     already within a few tiles — which is what makes running for the hall a
     real escape rather than a delaying tactic. */
  function raiderTarget(r) {
    let best = null, bd = 7, kind = null;
    for (const v of S.folk) {
      const d = Math.hypot(v.x - r.x, v.y - r.y);
      if (d < bd) { bd = d; best = v; kind = 'folk'; }
    }
    if (best) return { kind, ref: best };
    bd = 1e9;
    for (const b of S.builds.values()) {
      if (!b.def.hp) continue;
      const d = Math.hypot(b.x - r.x, b.y - r.y);
      if (d < bd) { bd = d; best = b; kind = 'build'; }
    }
    return best ? { kind, ref: best } : (S.hall ? { kind: 'build', ref: S.hall } : null);
  }

  function tickRaider(r, dt) {
    if (r.hurtT > 0) r.hurtT -= dt;
    if (r.cd > 0) r.cd -= dt;
    r.repath -= dt;

    if (!r.target || r.repath <= 0 || (r.target.kind === 'folk' && r.target.ref.hp <= 0) ||
      (r.target.kind === 'build' && !S.builds.has(r.target.ref.id))) {
      r.target = raiderTarget(r);
      r.repath = 1.3 + Math.random();
      r.path = null;
    }
    if (!r.target) return;
    const t = r.target.ref;
    const tx = r.target.kind === 'folk' ? t.x : t.x + (t.def.fw - 1) / 2;
    const ty = r.target.kind === 'folk' ? t.y : t.y + (t.def.fh - 1) / 2;
    const d = Math.hypot(tx - r.x, ty - r.y);
    const reach = Math.max(r.target.kind === 'folk' ? 1.0 : 1.6, r.kind.range || 0);

    if (d <= reach) {
      r.face = faceOf(tx - r.x, ty - r.y);
      if (r.cd <= 0) {
        r.cd = 1;
        SFX.hit();
        if (r.target.kind === 'folk') {
          t.hp -= r.kind.dmg; t.hurtT = 0.25;
          if (t.hp <= 0) killFolk(t);
        } else {
          t.hp -= r.kind.dmg * 0.9; t.hurtT = 0.2;
          if (t.hp <= 0) { const raze = t; removeBuild(raze, true); S.lost++; toast(raze.def.name + ' destroyed'); }
        }
      }
      return;
    }

    /* Walls are not obstacles to a raider, they are slow doors. The router is
       asked with smash on, so it will still prefer an open gate or a way
       round; when the cheapest route really does go through a palisade the
       raider stops at it and cuts. */
    if (!r.path || r.pi >= (r.path ? r.path.length : 0)) {
      const gx = clamp(Math.round(tx), 0, MW - 1), gy = clamp(Math.round(ty), 0, MH - 1);
      const p = W.route(S.world, Math.round(r.x), Math.round(r.y), gx, gy,
        { smash: true, gateOpen: gateOpenAt, budget: 5000 });
      r.path = p; r.pi = 0;
      if (!p) { r.x += (tx - r.x) * dt * 0.4; r.y += (ty - r.y) * dt * 0.4; return; }
    }
    const step = r.path[r.pi];
    if (step !== undefined) {
      const si = step, sx = si % MW, sy = si / MW | 0;
      const blockId = S.world.occ[si];
      const wall = S.world.wall[si];
      if ((wall && !(wall === 3 && gateOpenAt(si))) || (blockId && blockId !== (r.target.kind === 'build' ? t.id : -1))) {
        const b = findStructure(sx, sy);
        if (b) {
          r.face = faceOf(sx - r.x, sy - r.y);
          if (r.cd <= 0) {
            r.cd = 1; b.hp -= r.kind.dmg * 0.9; b.hurtT = 0.2; SFX.hit();
            if (b.hp <= 0) { removeBuild(b, true); S.lost++; r.path = null; }
          }
          return;
        }
        S.world.wall[si] = 0; r.path = null; return;
      }
    }
    if (advance(r, dt, r.kind.speed)) r.path = null;
  }

  function findStructure(x, y) {
    const i = W.idx(x, y);
    const id = S.world.occ[i];
    if (id && S.builds.has(id)) return S.builds.get(id);
    for (const b of S.builds.values())
      if (b.def.wall && x >= b.x && x < b.x + b.def.fw && y >= b.y && y < b.y + b.def.fh) return b;
    return null;
  }

  function killRaider(r) {
    const i = S.raiders.indexOf(r);
    if (i >= 0) S.raiders.splice(i, 1);
    S.kills++;
    S.score += r.kind.worth * 4;
    gain('coin', Math.ceil(r.kind.worth / 2));
    popup(r.x, r.y, '+' + Math.ceil(r.kind.worth / 2), RES_COLOUR.coin);
    for (let k = 0; k < 6; k++)
      S.sparks.push({ x: r.x, y: r.y, vx: (Math.random() - 0.5) * 3, vy: (Math.random() - 0.5) * 3, t: 0.5, c: '#a83a50' });
  }

  function killFolk(v) {
    const i = S.folk.indexOf(v);
    if (i >= 0) S.folk.splice(i, 1);
    if (v.place) { const b = S.builds.get(v.place); if (b) b.staff = b.staff.filter(id => id !== v.id); }
    if (S.sel && S.sel.kind === 'folk' && S.sel.ref === v) { S.sel = null; showInspect(null); }
    if (S.sendMode === v) S.sendMode = null;
    S.cheer -= 6;
    toast(v.name + ' was killed');
    assignHomes();
    if (!S.folk.length) lose('Nobody is left alive.');
  }

  function nearestRaider(x, y, r) {
    let best = null, bd = r * r;
    for (const e of S.raiders) {
      const d = (e.x - x) * (e.x - x) + (e.y - y) * (e.y - y);
      if (d < bd) { bd = d; best = e; }
    }
    return best;
  }

  /* ---------------------------------------------------------------- economy -- */

  function production(dt) {
    S.prodT += dt;
    if (S.prodT < 1) return;
    const step = S.prodT; S.prodT = 0;

    for (const b of S.builds.values()) {
      if (!b.done || !b.def.makes) continue;
      const staffed = b.staff.length > 0 || !b.def.jobs;
      if (!staffed) continue;
      b.timer += step;
      const m = b.def.makes;
      if (b.timer < m.rate) continue;
      /* The cycle only resets once it actually runs: a workshop that is a plank
         short this second should produce the moment the plank lands, not stand
         idle for another full rate. */
      if (!RES.every(r => (S.res[r] || 0) >= (m.from[r] || 0))) { b.timer = m.rate; continue; }
      b.timer = 0;
      for (const r of RES) if (m.from[r]) S.res[r] -= m.from[r];
      for (const r of RES) if (m.to[r]) { gain(r, m.to[r]); popup(b.x + 1, b.y, '+' + m.to[r], RES_COLOUR[r]); }
    }

    // towers loose arrows
    for (const b of S.builds.values()) {
      if (!b.done || !b.def.shoot) continue;
      b.timer += step;
      if (b.timer < 0.9) continue;
      const foe = nearestRaider(b.x + 1, b.y + 1, b.def.shoot.range);
      if (!foe) continue;
      b.timer = 0;
      S.arrows.push({ x: b.x + 1, y: b.y + 1, tx: foe.x, ty: foe.y, t: 0, foe, dmg: b.def.shoot.dps });
      SFX.bow();
    }

    // rations
    const pop = S.folk.length;
    S.res.food = Math.max(0, S.res.food - pop * 0.11 * step);
    S.starving = S.res.food <= 0;
    if (S.starving) for (const v of S.folk) v.hp -= 1.2 * step;

    // happiness settles toward what the settlement actually offers
    const homeless = S.folk.filter(v => !v.home).length;
    S.cheerTarget = clamp(52 + (S.buildCheer || 0) - homeless * 5 -
      (S.res.food <= 0 ? 38 : 0) - Math.max(0, pop - 14) * 1.2 - S.lost * 2, 0, 100);
    S.cheer += (S.cheerTarget - S.cheer) * Math.min(1, step * 0.35);

    // new settlers
    S.growT = (S.growT || 0) + step;
    if (S.growT > 12) {
      S.growT = 0;
      if (S.cheer > 55 && S.res.food > 40 && S.folk.length < (S.beds || 0)) {
        const h = S.hall;
        addFolk(h.x + 0.5 + (Math.random() - 0.5), h.y + 2.2, 'worker');
        assignHomes();
        toast('A settler has arrived');
      }
    }
  }

  function growCrops(dt) {
    S.growC = (S.growC || 0) + dt;
    if (S.growC < 0.5) return;
    const step = S.growC; S.growC = 0;
    for (const b of S.builds.values()) {
      if (!b.done || !b.def.field) continue;
      const hands = 1 + b.staff.length;
      footprint(b.def, b.x, b.y, (px, py) => {
        const i = W.idx(px, py);
        if (!S.world.crop[i] || S.world.crop[i] >= 5) return;
        S.world.cropT[i] += step * hands * (0.6 + S.cheer / 160);
        if (S.world.cropT[i] > 9) { S.world.cropT[i] = 0; S.world.crop[i]++; }
      });
    }
    for (let i = 0; i < W.N; i++) {
      if (S.world.regrow[i] > 0) {
        S.world.regrow[i] -= step;
        if (S.world.regrow[i] <= 0) {
          const k = W.nodeKey(S.world, i);
          if (k && NODES[k].regrow) S.world.amt[i] = NODES[k].amount;
        }
      }
    }
  }

  /* ------------------------------------------------------------------ clock -- */

  function tickClock(dt) {
    const before = S.hour;
    S.hour += dt * (24 / S.dayLen);
    if (S.hour >= 24) {
      S.hour -= 24; S.day++;
      if (S.day >= WIN_DAY) { win(); return; }
    }
    const night = S.hour >= 20 || S.hour < 6;
    if (night !== S.night) {
      S.night = night;
      if (night) {
        banner('NIGHT ' + S.day);
        for (const b of S.builds.values()) if (b.def.gate && b.gateMode === 'auto') b.open = false;
        if (S.day >= 2 && S.waveNight !== S.day) { S.waveNight = S.day; spawnWave(); }
      } else {
        banner('DAY ' + S.day);
        SFX.dawn();
        for (const b of S.builds.values()) if (b.def.gate && b.gateMode === 'auto') b.open = true;
        for (const v of S.folk) { v.asleep = false; if (v.state === 'sleep') decide(v); }
        // stragglers scatter at first light
        for (const r of S.raiders.slice()) if (Math.random() < 0.5) killRaider(r);
      }
    }
    // weather: a front rolls through every couple of days
    S.rainT -= dt;
    if (S.rainT <= 0) {
      S.rainT = 30 + Math.random() * 70;
      S.rainWant = Math.random() < 0.34 ? 1 : 0;
    }
    S.rain += ((S.rainWant || 0) - S.rain) * Math.min(1, dt * 0.5);
    if (before > S.hour) assignHomes();
  }

  /* ------------------------------------------------------------------- feed -- */

  function popup(x, y, text, colour) { S.pops.push({ x, y, text, colour, t: 0 }); }
  function toast(msg) { S.msg = msg; S.msgT = 2.6; }
  let bannerT = 0;
  function banner(txt) { el.banner.textContent = txt; bannerT = 2.4; }

  /* -------------------------------------------------------------------- UI -- */

  const paletteCells = [];
  function buildRail() {
    for (const c of CATS) {
      const b = mk('button', 'cat', el.rail);
      mk('i', null, b).style.background = c.tint;
      mk('span', null, b, c.name);
      b.addEventListener('click', () => { S.cat = c.id; SFX.pick(); refreshPalette(); });
      b._cat = c.id;
      c._btn = b;
    }
  }

  function refreshPalette() {
    el.palette.innerHTML = '';
    paletteCells.length = 0;
    for (const c of CATS) c._btn.classList.toggle('on', c.id === S.cat);
    for (const def of BUILD) {
      if (def.cat !== S.cat) continue;
      const cell = mk('button', 'cell', el.palette);
      const ic = mk('canvas', null, cell);
      ic.width = 32; ic.height = 32;
      drawPaletteIcon(ic, def);
      mk('em', null, cell, def.name);
      cell.addEventListener('click', () => {
        S.tool = S.tool === def ? null : def;
        S.sel = null;
        SFX.pick();
        refreshPalette();
        showCard(S.tool);
      });
      cell.addEventListener('mouseenter', () => showCard(def));
      cell.addEventListener('mouseleave', () => showCard(S.tool));
      cell._def = def;
      paletteCells.push(cell);
    }
    syncPalette();
  }

  /* Affordability is re-read every frame rather than on spend, because the
     stockpile also moves on its own — a hauler arriving can make something
     affordable with no click involved. */
  function syncPalette() {
    for (const cell of paletteCells) {
      const d = cell._def;
      cell.classList.toggle('on', S.tool === d);
      cell.classList.toggle('poor', !d.demolish && !has(d.cost));
    }
  }

  function drawPaletteIcon(icv, def) {
    const g = icv.getContext('2d');
    g.imageSmoothingEnabled = false;
    if (def.spr) {
      const f = sprFrame(def.spr[0], def.spr[1], 0);
      if (f) g.drawImage(f.cv, 0, 0);
      return;
    }
    if (def.wall) {
      const sheet = def.wall === 2 ? ART.rampart : ART.palisade;
      if (sheet && sheet[10]) { g.drawImage(sheet[10], 0, 8); g.drawImage(sheet[10], 16, 8); }
      return;
    }
    if (def.ground !== undefined && ART.ground) { g.drawImage(ART.ground[def.ground], 8, 8); return; }
    if (def.field) {
      const f = sprFrame('farm_crops', def.field === 'herb' ? 'carrot3' : 'wheat4', 0);
      if (f) g.drawImage(f.cv, 0, 0);
      return;
    }
    if (def.demolish) {
      const f = sprFrame('hold_site', 'ruin', 0);
      if (f) g.drawImage(f.cv, 0, 0);
    }
  }

  function showCard(def) {
    if (!def) { el.card.classList.add('hidden'); return; }
    el.card.classList.remove('hidden');
    el.cardName.textContent = def.name;
    el.cardCost.textContent = def.demolish ? 'recovers a third' : costText(def.cost);
    el.cardDesc.textContent = def.desc;
  }

  /* The inspector is rebuilt from scratch on selection change and then only
     its numbers are poked each frame — rebuilding it every frame would drop
     the button the player is currently reaching for. */
  let inspBody = null;
  function showInspect(sel) {
    el.insp.innerHTML = '';
    inspBody = null;
    if (!sel) { el.insp.classList.add('hidden'); return; }
    el.insp.classList.remove('hidden');

    const head = mk('div', 'ihead', el.insp);
    const icv = mk('canvas', 'iface', head);
    icv.width = 32; icv.height = 32;
    const g = icv.getContext('2d');
    g.imageSmoothingEnabled = false;
    const rows = mk('div', 'imeta', head);

    if (sel.kind === 'folk') {
      const v = sel.ref;
      const f = sprFrame(v.role === 'soldier' ? 'tiny_blade' : 'tiny_drudge', 'idle_down', 0);
      if (f) g.drawImage(f.cv, 0, 0);
      mk('b', null, rows, v.name);
      mk('span', null, rows, v.role === 'soldier' ? 'Soldier' : 'Settler');
      const stats = mk('div', 'istats', el.insp);
      const hp = statRow(stats, 'Health', '#f2606a');
      const at = statRow(stats, 'Attack', '#e8b23a');
      const wk = statRow(stats, 'Work', '#7fe0a8');
      const acts = mk('div', 'iacts', el.insp);
      const arm = mk('button', null, acts, 'Take up arms');
      arm.addEventListener('click', () => {
        if (v.role === 'soldier') { v.role = 'worker'; v.maxHp = 42; v.hp = Math.min(v.hp, 42); v.atk = 3; }
        else if (soldierRoom()) { v.role = 'soldier'; v.maxHp = 70; v.hp = 70; v.atk = 10 + (S.arms || 0); }
        else { toast('Build a barracks first'); SFX.deny(); return; }
        if (v.place) { const b = S.builds.get(v.place); if (b) b.staff = b.staff.filter(id => id !== v.id); }
        v.place = 0; decide(v); SFX.pick(); showInspect(sel);
      });
      const send = mk('button', null, acts, 'Send here');
      send.addEventListener('click', () => {
        S.sendMode = v; toast('Click a tile to send ' + v.name); SFX.pick();
      });
      inspBody = () => {
        hp.set(v.hp / v.maxHp, Math.ceil(v.hp) + ' / ' + v.maxHp);
        at.set(v.atk / 20, String(v.atk));
        const place = S.builds.get(v.place);
        wk.set(1, v.asleep ? 'Asleep' : place ? place.def.name : 'Unassigned');
        arm.textContent = v.role === 'soldier' ? 'Stand down' : 'Take up arms';
      };
    } else {
      const b = sel.ref;
      drawPaletteIcon(icv, b.def);
      mk('b', null, rows, b.def.name);
      mk('span', null, rows, b.def.desc);
      const stats = mk('div', 'istats', el.insp);
      const hp = statRow(stats, 'Health', '#f2606a');
      const st = statRow(stats, 'Status', '#9fd0ff');
      let modeBtns = null;
      if (b.def.gate) {
        const acts = mk('div', 'iacts', el.insp);
        modeBtns = ['closed', 'open', 'auto'].map(m => {
          const btn = mk('button', null, acts, m === 'auto' ? 'Auto' : m === 'open' ? 'Open' : 'Shut');
          btn.addEventListener('click', () => {
            b.gateMode = m;
            b.open = m === 'open' ? true : m === 'closed' ? false : !S.night;
            SFX.pick();
          });
          btn._m = m;
          return btn;
        });
      }
      if (b.def !== HALL) {
        const acts = mk('div', 'iacts', el.insp);
        const raze = mk('button', 'warn', acts, 'Demolish');
        raze.addEventListener('click', () => { refund(b.def); removeBuild(b, false); S.sel = null; showInspect(null); SFX.place(); });
      }
      inspBody = () => {
        hp.set(b.hp / b.maxHp, Math.ceil(b.hp) + ' / ' + b.maxHp);
        st.set(b.done ? 1 : b.prog / b.work, b.done
          ? (b.def.jobs ? b.staff.length + ' / ' + b.def.jobs + ' working' : 'Standing')
          : 'Building ' + Math.floor(b.prog / b.work * 100) + '%');
        if (modeBtns) for (const btn of modeBtns) btn.classList.toggle('on', btn._m === b.gateMode);
      };
    }
    inspBody();
  }

  function statRow(parent, label, colour) {
    const row = mk('div', 'srow', parent);
    mk('span', null, row, label);
    const bar = mk('div', 'sbar', row);
    const fill = mk('i', null, bar);
    fill.style.background = colour;
    const num = mk('em', null, row, '');
    return { set(frac, text) { fill.style.width = Math.round(clamp(frac, 0, 1) * 100) + '%'; num.textContent = text; } };
  }

  const soldierRoom = () => S.folk.filter(v => v.role === 'soldier').length < (S.guardCap || 0);

  /* ---------------------------------------------------------------- input -- */

  const keys = {};
  addEventListener('keydown', e => {
    /* The arrows pan the map, so they must not also scroll the page, and space
       must not re-fire whichever HUD button was clicked last. */
    if (['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight', ' '].includes(e.key)) e.preventDefault();
    keys[(e.key || '').toLowerCase()] = true;
    const k = (e.key || '').toLowerCase();
    if (k === 'escape') { S.tool = null; S.sel = null; S.sendMode = null; refreshPalette(); showCard(null); showInspect(null); }
    if (k === 'p') togglePause();
    if (k === 'm') toggleMute();
    if (k === '1') setSpeed(1);
    if (k === '2') setSpeed(2);
    if (k === '3') setSpeed(3);
  });
  addEventListener('keyup', e => { keys[(e.key || '').toLowerCase()] = false; });
  addEventListener('resize', resize);
  addEventListener('blur', () => { for (const k in keys) keys[k] = false; });

  function screenToTile(ev) {
    const r = cv.getBoundingClientRect();
    const sx = (ev.clientX - r.left) * (cv.width / Math.max(1, r.width));
    const sy = (ev.clientY - r.top) * (cv.height / Math.max(1, r.height));
    return { x: Math.floor((sx / S.zoom + S.cam.x) / T), y: Math.floor((sy / S.zoom + S.cam.y) / T) };
  }

  cv.addEventListener('mousemove', ev => {
    const t = screenToTile(ev);
    S.hover = t;
    if (S.drag) {
      if (S.drag.tool) { if (S.drag.painted !== W.idx(clamp(t.x, 0, MW - 1), clamp(t.y, 0, MH - 1))) tryPlaceAt(t); }
      else {
        const r = cv.getBoundingClientRect();
        const scale = cv.width / Math.max(1, r.width) / S.zoom;
        S.cam.x -= (ev.clientX - S.drag.mx) * scale;
        S.cam.y -= (ev.clientY - S.drag.my) * scale;
        S.drag.mx = ev.clientX; S.drag.my = ev.clientY;
        S.drag.moved += 1;
        clampCam();
      }
    }
  });
  cv.addEventListener('mousedown', ev => {
    SFX.on();                                    // browsers only allow audio from a gesture
    if (!S.running) return;
    const t = screenToTile(ev);
    if (S.sendMode) {
      const v = S.sendMode; S.sendMode = null;
      if (W.inb(t.x, t.y) && goTo(v, W.idx(t.x, t.y))) { v.state = 'wander'; v.timer = 0; }
      return;
    }
    if (S.tool) { S.drag = { tool: true, painted: -1 }; tryPlaceAt(t); return; }
    S.drag = { tool: false, mx: ev.clientX, my: ev.clientY, moved: 0, t };
  });
  const endDrag = () => {
    if (S.drag && !S.drag.tool && S.drag.moved < 3) pick(S.drag.t);
    S.drag = null;
  };
  cv.addEventListener('mouseup', endDrag);
  cv.addEventListener('mouseleave', () => { S.drag = null; });
  cv.addEventListener('contextmenu', ev => { ev.preventDefault(); S.tool = null; refreshPalette(); showCard(null); });
  cv.addEventListener('wheel', ev => {
    ev.preventDefault();
    S.zoom = clamp(S.zoom + (ev.deltaY > 0 ? -1 : 1), 2, 5);
    clampCam();
  });
  // touch: one finger pans, and a tap acts as a click
  cv.addEventListener('touchstart', ev => {
    SFX.on();
    const t0 = ev.touches[0]; if (!t0) return;
    ev.preventDefault();
    const t = screenToTile(t0);
    if (S.tool) { S.drag = { tool: true, painted: -1 }; tryPlaceAt(t); }
    else S.drag = { tool: false, mx: t0.clientX, my: t0.clientY, moved: 0, t };
  }, { passive: false });
  cv.addEventListener('touchmove', ev => {
    const t0 = ev.touches[0]; if (!t0 || !S.drag) return;
    ev.preventDefault();
    const t = screenToTile(t0);
    S.hover = t;
    if (S.drag.tool) { if (S.drag.painted !== W.idx(clamp(t.x, 0, MW - 1), clamp(t.y, 0, MH - 1))) tryPlaceAt(t); }
    else {
      const r = cv.getBoundingClientRect();
      const scale = cv.width / Math.max(1, r.width) / S.zoom;
      S.cam.x -= (t0.clientX - S.drag.mx) * scale;
      S.cam.y -= (t0.clientY - S.drag.my) * scale;
      S.drag.mx = t0.clientX; S.drag.my = t0.clientY; S.drag.moved += 1;
      clampCam();
    }
  }, { passive: false });
  cv.addEventListener('touchend', endDrag);

  function tryPlaceAt(t) {
    if (!W.inb(t.x, t.y)) return;
    S.drag && (S.drag.painted = W.idx(t.x, t.y));
    if (place(S.tool, t.x, t.y)) syncPalette();
  }

  function pick(t) {
    if (!t || !W.inb(t.x, t.y)) { S.sel = null; showInspect(null); return; }
    let best = null, bd = 1.1;
    for (const v of S.folk) {
      const d = Math.hypot(v.x - t.x, v.y - t.y);
      if (d < bd) { bd = d; best = { kind: 'folk', ref: v }; }
    }
    if (!best) {
      const b = findStructure(t.x, t.y);
      if (b) best = { kind: 'build', ref: b };
    }
    S.sel = best;
    showInspect(best);
    if (best) SFX.pick();
  }

  /* The map edge is a hard stop: letting the camera drift past it puts a band
     of dead black on screen, which reads as a rendering bug rather than as the
     edge of the world. When the viewport is wider than the map, centre it. */
  function clampCam() {
    const vw = cv.width / S.zoom, vh = cv.height / S.zoom;
    const mx = MW * T - vw, my = MH * T - vh;
    S.cam.x = mx <= 0 ? mx / 2 : clamp(S.cam.x, 0, mx);
    S.cam.y = my <= 0 ? my / 2 : clamp(S.cam.y, 0, my);
  }

  let sized = false;
  function resize() {
    const dpr = Math.min(2, window.devicePixelRatio || 1);
    cv.width = Math.max(320, Math.floor(innerWidth * dpr));
    cv.height = Math.max(240, Math.floor(innerHeight * dpr));
    /* The zoom is only chosen once. Mobile browsers fire resize every time the
       URL bar slides away, and recomputing it here threw away whatever the
       player had just set with the wheel. */
    if (!sized) { sized = true; S.zoom = clamp(Math.round(Math.min(cv.width, cv.height) / 260), 2, 5); }
    ctx.imageSmoothingEnabled = false;
    clampCam();
  }

  /* --------------------------------------------------------- speed / flow -- */

  const spdBtns = {};
  function setSpeed(n) {
    S.speed = n;
    S.paused = n === 0;
    for (const k in spdBtns) spdBtns[k].classList.toggle('on', Number(k) === n);
    el.pause.textContent = n === 0 ? 'RESUME' : 'PAUSE';
  }
  function toggleMute() {
    const m = SFX.toggle();
    el.mute.classList.toggle('off', m);
    el.mute.textContent = m ? 'MUTED' : 'SOUND';
  }

  const togglePause = () => setSpeed(S.speed === 0 ? (S.lastSpeed || 1) : (S.lastSpeed = S.speed, 0));

  function wireChrome() {
    for (const n of [0, 1, 2, 3]) {
      const b = $('#btn-spd' + n);
      if (!b) continue;
      spdBtns[n] = b;
      b.addEventListener('click', () => { if (n) S.lastSpeed = n; setSpeed(n); SFX.pick(); });
    }
    el.pause.addEventListener('click', togglePause);
    el.mute.title = 'Sound (M)';
    el.mute.addEventListener('click', toggleMute);
    el.again.addEventListener('click', () => { el.over.classList.add('hidden'); startRun(S.diff); });
  }

  /* ------------------------------------------------------------ start / end -- */

  function buildPicker() {
    for (const d of DIFFS) {
      const b = mk('button', 'pickitem', el.picker);
      mk('b', null, b, d.name);
      mk('span', null, b, d.sub);
      b.addEventListener('click', () => startRun(d));
    }
    const best = Number(localStorage.getItem('hh_best') || 0);
    el.best.textContent = best ? 'Longest hold: day ' + best : '';
  }

  function startRun(diff) {
    bakeArt();
    S.diff = diff;
    S.world = W.make((diff.id.charCodeAt(0) * 7919) ^ 0x5bf03635);
    S.res = {}; for (const r of RES) S.res[r] = diff.start[r] || 0;
    S.dayLen = diff.day;
    S.folk.length = 0; S.raiders.length = 0; S.arrows.length = 0;
    S.pops.length = 0; S.sparks.length = 0;
    S.builds.clear(); S.nextId = 1;
    S.day = 1; S.hour = 7; S.night = false; S.rain = 0; S.rainT = 0; S.rainWant = 0;
    S.cheer = 62; S.cheerTarget = 62;
    S.score = 0; S.kills = 0; S.raised = 0; S.lost = 0; S.wave = 0; S.waveNight = 0;
    S.tool = null; S.sel = null; S.sendMode = null; S.over = false; S.won = false;
    S.cat = 'home'; nameSeq = 0;
    S.prodT = 0; S.growT = 0; S.growC = 0; S.starving = false; S.lastSpeed = 1;

    // the hall, pre-raised at the centre of the cleared plaza
    const hx = (MW >> 1) - 1, hy = (MH >> 1) - 1;
    const hall = { id: S.nextId++, def: HALL, x: hx, y: hy, hp: HALL.hp, maxHp: HALL.hp,
      done: true, prog: 0, work: 0, staff: [], gateMode: 'auto', open: true, timer: 0, anim: 0 };
    S.builds.set(hall.id, hall);
    S.hall = hall;
    footprint(HALL, hx, hy, (px, py) => { S.world.occ[W.idx(px, py)] = hall.id; });
    recomputeCaps();

    for (let k = 0; k < diff.folk; k++) {
      const a = k / diff.folk * TAU;
      addFolk(hx + 1 + Math.cos(a) * 2.5, hy + 3 + Math.sin(a) * 1.5, 'worker');
    }
    assignHomes();

    S.cam.x = (hx + 1) * T - cv.width / S.zoom / 2;
    S.cam.y = (hy + 1) * T - cv.height / S.zoom / 2;
    clampCam();
    dirtyGround();

    el.title.classList.add('hidden');
    el.over.classList.add('hidden');
    el.hud.classList.remove('hidden');
    refreshPalette();
    showCard(null);
    showInspect(null);
    setSpeed(1);
    S.running = true;
    banner('DAY 1');
    toast('Raise huts before nightfall');
  }

  function finish(title, sub, won) {
    if (S.over) return;
    S.over = true; S.won = won; S.running = false;
    const best = Number(localStorage.getItem('hh_best') || 0);
    if (S.day > best) localStorage.setItem('hh_best', String(S.day));
    el.overTitle.textContent = title;
    el.overSub.textContent = sub;
    el.overStats.innerHTML = '';
    const stats = [['Days held', S.day], ['Buildings raised', S.raised],
      ['Raiders cut down', S.kills], ['Structures lost', S.lost], ['Renown', Math.floor(S.score)]];
    for (const [k, v] of stats) {
      const row = mk('div', 'orow', el.overStats);
      mk('span', null, row, k);
      mk('b', null, row, String(v));
    }
    el.over.classList.remove('hidden');
  }
  const lose = why => finish('THE HOLD IS BROKEN', why + ' Day ' + S.day + '.', false);
  const win = () => finish('HEARTHHOLD STANDS', 'Twelve days and eleven nights. The valley is yours.', true);

  /* ---------------------------------------------------------------- render -- */

  /* The terrain is a single pre-rendered canvas of the whole map, redrawn only
     when the ground actually changes. Blitting 3,136 individual tiles every
     frame was the entire frame budget on a phone; blitting one is free. */
  let groundCv = null, groundDirty = true;
  const dirtyGround = () => { groundDirty = true; };
  function repaintGround() {
    if (!groundCv) {
      groundCv = document.createElement('canvas');
      groundCv.width = MW * T; groundCv.height = MH * T;
    }
    const g = groundCv.getContext('2d');
    g.imageSmoothingEnabled = false;
    for (let y = 0; y < MH; y++) for (let x = 0; x < MW; x++) {
      const t = ART.ground[S.world.ground[W.idx(x, y)]];
      if (t) g.drawImage(t, x * T, y * T);
    }
    groundDirty = false;
  }

  function draw() {
    const w = cv.width, h = cv.height;
    ctx.imageSmoothingEnabled = false;
    ctx.fillStyle = '#10141f';
    ctx.fillRect(0, 0, w, h);
    if (!S.world) return;
    if (groundDirty) repaintGround();

    ctx.save();
    ctx.scale(S.zoom, S.zoom);
    ctx.translate(-Math.round(S.cam.x), -Math.round(S.cam.y));

    const vw = w / S.zoom, vh = h / S.zoom;
    const x0 = clamp(Math.floor(S.cam.x / T) - 1, 0, MW - 1);
    const y0 = clamp(Math.floor(S.cam.y / T) - 2, 0, MH - 1);
    const x1 = clamp(Math.ceil((S.cam.x + vw) / T) + 1, 0, MW - 1);
    const y1 = clamp(Math.ceil((S.cam.y + vh) / T) + 3, 0, MH - 1);

    ctx.drawImage(groundCv, x0 * T, y0 * T, (x1 - x0 + 1) * T, (y1 - y0 + 1) * T,
      x0 * T, y0 * T, (x1 - x0 + 1) * T, (y1 - y0 + 1) * T);

    // crops sit flat on the tilled ground, below everything with a silhouette
    for (let y = y0; y <= y1; y++) for (let x = x0; x <= x1; x++) {
      const i = W.idx(x, y);
      if (!S.world.crop[i]) continue;
      const f = sprFrame('farm_crops', 'wheat' + S.world.crop[i], 0);
      if (f) ctx.drawImage(f.cv, x * T - 8, y * T - 12);
    }

    // walls: flat, and never sorted, so a run reads as one continuous barrier
    for (let y = y0; y <= y1; y++) for (let x = x0; x <= x1; x++) {
      const i = W.idx(x, y), wl = S.world.wall[i];
      if (!wl || wl === 3) continue;
      const sheet = wl === 2 ? ART.rampart : ART.palisade;
      const tile = sheet[W.wallMask(S.world, x, y)];
      if (tile) ctx.drawImage(tile, x * T, y * T);
    }

    /* Everything with height goes into one list sorted by its ground line, so
       a villager walking behind a house is behind it and in front on the way
       back. Sorting by the footprint's bottom edge rather than the sprite's
       is what keeps tall roofs from popping in front of their own doorstep. */
    const items = [];
    for (let y = y0; y <= y1; y++) for (let x = x0; x <= x1; x++) {
      const i = W.idx(x, y);
      const d = W.nodeDef(S.world, i);
      if (!d) continue;
      const key = W.nodeKey(S.world, i);
      const shown = (d.res && S.world.amt[i] <= 0 && d.regrow) ? 'bush' : key;
      items.push({ y: y + 0.5, kind: 'node', x, ty: y, spr: NODES[shown].spr });
    }
    for (const b of S.builds.values()) {
      if (b.x > x1 + 2 || b.y > y1 + 2 || b.x + b.def.fw < x0 - 2 || b.y + b.def.fh < y0 - 2) continue;
      items.push({ y: b.y + b.def.fh, kind: 'build', b });
    }
    for (const v of S.folk) items.push({ y: v.y + 0.4, kind: 'folk', v });
    for (const r of S.raiders) items.push({ y: r.y + 0.4, kind: 'raid', r });
    items.sort((a, b) => a.y - b.y);

    for (const it of items) {
      if (it.kind === 'node') {
        const f = sprFrame(it.spr[0], it.spr[1], 0);
        if (f) ctx.drawImage(f.cv, it.x * T - 8, it.ty * T - 16);
      } else if (it.kind === 'build') drawBuild(it.b);
      else if (it.kind === 'folk') drawFolk(it.v);
      else drawRaider(it.r);
    }

    // arrows in flight
    ctx.fillStyle = '#e8e2d0';
    for (const a of S.arrows) {
      const px = lerp(a.x, a.tx, a.t) * T + 8, py = lerp(a.y, a.ty, a.t) * T + 8 - Math.sin(a.t * Math.PI) * 10;
      ctx.fillRect(px - 1, py - 1, 2, 2);
    }
    ctx.globalAlpha = 1;
    for (const s of S.sparks) {
      ctx.fillStyle = s.c;
      ctx.globalAlpha = clamp(s.t * 2, 0, 1);
      ctx.fillRect(s.x * T + 8, s.y * T + 8, 2, 2);
    }
    ctx.globalAlpha = 1;

    drawGhost();
    drawSelection();
    ctx.restore();

    drawNight(w, h);
    drawWeather(w, h);
    drawFloaters();
  }

  function drawBuild(b) {
    const px = (b.x + b.def.fw / 2) * T - 16;
    const py = (b.y + b.def.fh) * T - 32;
    if (!b.done) {
      const stage = b.prog / b.work;
      const st = stage < 0.34 ? 'site_frame' : stage < 0.7 ? 'site_half' : 'site_near';
      const f = sprFrame('hold_site', st, 0);
      if (f) ctx.drawImage(f.cv, px, py);
      ctx.fillStyle = '#0008'; ctx.fillRect(px + 4, py - 6, 24, 4);
      ctx.fillStyle = '#7fe0a8'; ctx.fillRect(px + 5, py - 5, Math.round(22 * stage), 2);
      return;
    }
    if (b.def.wall === 3) {                     // gate: its own two-tile sprite
      const f = sprFrame('hold_keep', b.open ? 'gate_open' : 'gate_closed', 0);
      if (f) ctx.drawImage(f.cv, b.x * T, b.y * T - 8);
    } else if (b.def.spr) {
      const f = spr(b.def.spr[0], b.def.spr[1], S.t + b.anim);
      if (f) ctx.drawImage(f.cv, px, py);
    } else if (b.def.field) {
      // fields draw through their crop tiles; only the frame posts show here
      ctx.fillStyle = '#4e2f1c';
      footprint(b.def, b.x, b.y, (x, y) => ctx.fillRect(x * T, y * T + T - 2, T, 2));
    }
    if (b.hurtT > 0) {
      ctx.globalAlpha = 0.5; ctx.fillStyle = '#ff6b6b';
      ctx.fillRect(b.x * T, b.y * T, b.def.fw * T, b.def.fh * T);
      ctx.globalAlpha = 1;
    }
    if (b.hp < b.maxHp) hpBar(b.x * T + 1, b.y * T - 4, b.def.fw * T - 2, b.hp / b.maxHp, '#f2606a');
  }

  function drawFolk(v) {
    const id = v.role === 'soldier' ? 'tiny_blade' : 'tiny_drudge';
    let state;
    if (v.asleep) state = 'idle_down';
    else if (v.carry) state = 'carry';
    else if (v.path) state = 'walk_' + v.face;
    else if (v.state === 'gather' || v.state === 'build' || v.state === 'harvest') state = 'attack_' + v.face;
    else state = 'idle_' + v.face;
    const f = spr(id, state, v.anim / 6 + v.id);
    if (!f) return;
    const px = Math.round(v.x * T) - 8, py = Math.round(v.y * T) - 22;
    if (v.asleep) { ctx.globalAlpha = 0.75; }
    ctx.drawImage(f.cv, px, py);
    ctx.globalAlpha = 1;
    if (v.hurtT > 0) { ctx.globalAlpha = 0.6; ctx.drawImage(GB.tint(f.cv, '#ff8a8a', 1), px, py); ctx.globalAlpha = 1; }
    if (v.asleep) {
      ctx.fillStyle = '#cfe0ff';
      const z = Math.floor(S.t * 2) % 3;
      ctx.fillRect(px + 20, py + 2 - z * 2, 3, 3);
    }
    if (v.hp < v.maxHp) hpBar(px + 8, py + 2, 16, v.hp / v.maxHp, '#7fe0a8');
    if (S.sel && S.sel.kind === 'folk' && S.sel.ref === v) ring(v.x, v.y, '#fee761');
  }

  function drawRaider(r) {
    const state = r.path && r.pi < r.path.length ? 'walk_' + r.face : (r.cd > 0.6 ? 'attack_' + r.face : 'idle_' + r.face);
    const f = spr(r.kind.spr, state, r.anim / 6 + r.id);
    if (!f) return;
    const px = Math.round(r.x * T) - 8, py = Math.round(r.y * T) - 22;
    ctx.drawImage(f.cv, px, py);
    ctx.globalAlpha = 0.55;
    ctx.drawImage(GB.tint(f.cv, r.hurtT > 0 ? '#ffd0d0' : r.kind.wash, 1), px, py);
    ctx.globalAlpha = 1;
    hpBar(px + 8, py + 2, 16, r.hp / r.maxHp, '#d9536a');
  }

  function hpBar(x, y, w, frac, colour) {
    ctx.fillStyle = '#181425cc'; ctx.fillRect(x, y, w, 3);
    ctx.fillStyle = colour; ctx.fillRect(x, y, Math.max(0, Math.round(w * clamp(frac, 0, 1))), 3);
  }

  function ring(tx, ty, colour) {
    ctx.strokeStyle = colour; ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.ellipse(tx * T + 8, ty * T + 10, 9, 5, 0, 0, TAU);
    ctx.stroke();
  }

  function drawGhost() {
    if (!S.tool || !W.inb(S.hover.x, S.hover.y)) return;
    const d = S.tool, ok = canPlace(d, S.hover.x, S.hover.y) && (d.demolish || has(d.cost));
    ctx.globalAlpha = 0.34;
    ctx.fillStyle = ok ? '#7fe0a8' : '#f2606a';
    footprint(d, S.hover.x, S.hover.y, (x, y) => ctx.fillRect(x * T, y * T, T, T));
    ctx.globalAlpha = 0.72;
    if (d.spr) {
      const f = sprFrame(d.spr[0], d.spr[1], 0);
      if (f) ctx.drawImage(f.cv, (S.hover.x + d.fw / 2) * T - 16, (S.hover.y + d.fh) * T - 32);
    }
    ctx.globalAlpha = 1;
  }

  function drawSelection() {
    if (!S.sel) return;
    if (S.sel.kind === 'build') {
      const b = S.sel.ref;
      ctx.strokeStyle = '#fee761'; ctx.lineWidth = 1;
      ctx.strokeRect(b.x * T + 0.5, b.y * T + 0.5, b.def.fw * T - 1, b.def.fh * T - 1);
    }
  }

  /* Night is one dark wash with the light pools punched back out. The punching
     has to happen on a scratch canvas: destination-out on the main context
     would erase the settlement along with the wash and leave holes straight
     through to the page. Composited this way a torch lights whatever is under
     it — ground, walls, people — instead of being a glow drawn on top. */
  let nightCv = null;

  function drawNight(w, h) {
    const dusk = S.hour >= 19 && S.hour < 20 ? (S.hour - 19)
      : S.hour >= 20 || S.hour < 5 ? 1
        : S.hour >= 5 && S.hour < 7 ? 1 - (S.hour - 5) / 2 : 0;
    const dark = dusk * 0.72 + S.rain * 0.12;
    if (dark <= 0.01) return;
    if (!nightCv) nightCv = document.createElement('canvas');
    if (nightCv.width !== w || nightCv.height !== h) { nightCv.width = w; nightCv.height = h; }
    const n = nightCv.getContext('2d');
    n.setTransform(1, 0, 0, 1, 0, 0);
    n.globalCompositeOperation = 'source-over';
    n.globalAlpha = 1;
    n.clearRect(0, 0, w, h);
    n.fillStyle = '#0b1026';
    n.globalAlpha = Math.min(1, dark);
    n.fillRect(0, 0, w, h);
    n.globalAlpha = 1;
    n.globalCompositeOperation = 'destination-out';
    for (const b of S.builds.values()) {
      if (!b.done || !b.def.light) continue;
      const cx = ((b.x + b.def.fw / 2) * T - S.cam.x) * S.zoom;
      const cy = ((b.y + b.def.fh / 2) * T - S.cam.y) * S.zoom;
      const rad = b.def.light * T * S.zoom * (0.94 + Math.sin(S.t * 3 + b.anim) * 0.06);
      if (cx + rad < 0 || cy + rad < 0 || cx - rad > w || cy - rad > h) continue;
      const grd = n.createRadialGradient(cx, cy, rad * 0.15, cx, cy, rad);
      grd.addColorStop(0, 'rgba(0,0,0,0.92)');
      grd.addColorStop(0.55, 'rgba(0,0,0,0.42)');
      grd.addColorStop(1, 'rgba(0,0,0,0)');
      n.fillStyle = grd;
      n.fillRect(cx - rad, cy - rad, rad * 2, rad * 2);
    }
    n.globalCompositeOperation = 'source-over';
    ctx.drawImage(nightCv, 0, 0);
  }

  function drawWeather(w, h) {
    if (S.rain < 0.05) return;
    const f = spr('rpg_weather', 'rain', S.t);
    if (!f) return;
    ctx.save();
    ctx.globalAlpha = S.rain * 0.55;
    const s = 2;
    const ox = -((S.t * 40) % (f.w * s)), oy = -((S.t * 260) % (f.h * s));
    for (let y = oy; y < h; y += f.h * s)
      for (let x = ox; x < w; x += f.w * s)
        ctx.drawImage(f.cv, 0, 0, f.w, f.h, x, y, f.w * s, f.h * s);
    ctx.restore();
  }

  function drawFloaters() {
    ctx.save();
    ctx.textAlign = 'center';
    ctx.font = '700 ' + (7 * S.zoom) + 'px ui-monospace, monospace';
    for (const p of S.pops) {
      const px = (p.x * T + 8 - S.cam.x) * S.zoom;
      const py = (p.y * T - S.cam.y) * S.zoom - p.t * 26;
      ctx.globalAlpha = clamp(1.4 - p.t, 0, 1);
      ctx.fillStyle = '#181425';
      ctx.fillText(p.text, px + 1, py + 1);
      ctx.fillStyle = p.colour;
      ctx.fillText(p.text, px, py);
    }
    ctx.restore();
  }

  /* ------------------------------------------------------------------ HUD -- */

  let hudCache = {};
  function syncHud() {
    for (const r of RES) {
      const n = Math.floor(S.res[r] || 0);
      if (hudCache[r] !== n) { hudCache[r] = n; resEl[r].textContent = String(n); }
    }
    const pop = S.folk.length + ' / ' + (S.beds || 0);
    if (hudCache.pop !== pop) { hudCache.pop = pop; el.pop.textContent = pop; }
    const hh = Math.floor(S.hour), mm = Math.floor((S.hour - hh) * 60);
    const clock = String(hh).padStart(2, '0') + ':' + String(mm).padStart(2, '0');
    if (hudCache.clock !== clock) { hudCache.clock = clock; el.clock.textContent = clock; }
    if (hudCache.day !== S.day) { hudCache.day = S.day; el.day.textContent = 'DAY ' + S.day; }
    const sc = Math.floor(S.score);
    if (hudCache.score !== sc) { hudCache.score = sc; el.score.textContent = String(sc); }
    const cw = Math.round(S.cheer) + '%';
    if (hudCache.cheer !== cw) {
      hudCache.cheer = cw;
      el.cheerFill.style.width = cw;
      el.cheerFill.style.background = S.cheer > 60 ? '#7fe0a8' : S.cheer > 35 ? '#e8b23a' : '#f2606a';
    }
    const trend = S.cheerTarget - S.cheer > 1.5 ? '▲' : S.cheer - S.cheerTarget > 1.5 ? '▼' : '—';
    if (hudCache.trend !== trend) { hudCache.trend = trend; el.cheerArrow.textContent = trend; }
    el.toast.classList.toggle('hidden', S.msgT <= 0);
    if (S.msgT > 0 && hudCache.msg !== S.msg) { hudCache.msg = S.msg; el.toast.textContent = S.msg; }
    el.banner.classList.toggle('hidden', bannerT <= 0);
  }

  /* ----------------------------------------------------------------- loop -- */

  let last = 0;
  function frame(ts) {
    requestAnimationFrame(frame);
    const raw = last ? Math.min(0.05, (ts - last) / 1000) : 0.016;
    last = ts;
    S.t += raw;

    if (S.running && !S.over) {
      // camera keys work while paused: inspecting a frozen settlement is useful
      const pan = 620 * raw / S.zoom;
      if (keys.a || keys.arrowleft) S.cam.x -= pan;
      if (keys.d || keys.arrowright) S.cam.x += pan;
      if (keys.w || keys.arrowup) S.cam.y -= pan;
      if (keys.s || keys.arrowdown) S.cam.y += pan;
      if (keys.a || keys.d || keys.w || keys.s || keys.arrowleft || keys.arrowright ||
        keys.arrowup || keys.arrowdown) clampCam();

      const dt = raw * S.speed;
      if (dt > 0) {
        tickClock(dt);
        for (let k = S.folk.length - 1; k >= 0; k--) {
          const v = S.folk[k];
          if (v.hp <= 0) { killFolk(v); continue; }
          tickFolk(v, dt);
        }
        for (let k = S.raiders.length - 1; k >= 0; k--) tickRaider(S.raiders[k], dt);
        for (let k = S.arrows.length - 1; k >= 0; k--) {
          const a = S.arrows[k];
          a.t += dt * 2.4;
          if (a.t >= 1) {
            if (a.foe && S.raiders.includes(a.foe)) {
              a.foe.hp -= a.dmg; a.foe.hurtT = 0.2;
              if (a.foe.hp <= 0) killRaider(a.foe);
            }
            S.arrows.splice(k, 1);
          }
        }
        production(dt);
        growCrops(dt);
      }
    }

    for (let k = S.pops.length - 1; k >= 0; k--) { S.pops[k].t += raw; if (S.pops[k].t > 1.4) S.pops.splice(k, 1); }
    for (let k = S.sparks.length - 1; k >= 0; k--) {
      const s = S.sparks[k];
      s.x += s.vx * raw; s.y += s.vy * raw; s.t -= raw;
      if (s.t <= 0) S.sparks.splice(k, 1);
    }
    if (S.msgT > 0) S.msgT -= raw;
    if (bannerT > 0) bannerT -= raw;

    draw();
    /* The HUD keeps updating after the run ends so the final readouts match
       what actually happened — freezing it a frame early leaves the game-over
       screen quoting a population that is still alive. */
    if (S.world) syncHud();
    if (S.running) { syncPalette(); if (inspBody) inspBody(); }
  }

  /* ----------------------------------------------------------------- boot -- */

  function boot() {
    bakeArt();
    resize();
    buildResStrip();
    buildRail();
    buildPicker();
    wireChrome();
    if (navigator.maxTouchPoints > 0) document.body.classList.add('touch');
    requestAnimationFrame(frame);
  }

  boot();
})();
